"""o2a-proxy Python 包：协议转换代理核心（引擎 / 转换 / 配置 / 统计）。

自 v0.2 起，原根目录 proxy.py / proxy_async.py 的实现整体收拢到本包；
根目录保留同名文件作为兼容 shim（桌面端路径探测与旧导入方式不破）。
"""

from .base import (
    API_KEY,
    HAS_FCNTL,
    LISTEN_HOST,
    LISTEN_PORT,
    PROXY,
    PROXY_MAX_TOKENS,
    PROXY_MODEL,
    PROJECT_ROOT,
    STREAM_TIMEOUT,
    TARGET_URL,
    _auth_file_path,
    _config_file_path,
    _default_script_path,
    _normalize_openai_url,
    _project_root,
    _resolve_config_path,
    _responses_url,
    logger,
)
from .config import (
    Account,
    Service,
    _OPENAI_API_VALUES,
    _THINKING_MODES,
    _UPSTREAM_API_VALUES,
    _resolve_api_key,
    load_auth,
    load_config,
)
from .convert import (
    _ResponsesStreamTranslator,
    _anthropic_stop_reason,
    _apply_reasoning_to_chat,
    _apply_thinking_to_chat,
    _budget_to_effort,
    _chat_to_responses_json,
    _chat_usage_to_responses,
    _convert_usage,
    _extract_text,
    _infer_thinking_style,
    _responses_content_to_text,
    _responses_to_chat,
    _strip_cache_control,
    _tool_choice_any,
    _to_int,
    convert_request,
    convert_tool_input,
    detect_client,
    normalize_roles,
    resolve_mode,
    sse_event,
)
from .stats import (
    CacheStats,
    _stats,
    _stats_lock,
    get_account_summary,
    get_stats,
    is_cache_stats_enabled,
)

__version__ = "0.2.0"

__all__ = [
    "API_KEY",
    "Account",
    "CacheStats",
    "HAS_FCNTL",
    "LISTEN_HOST",
    "LISTEN_PORT",
    "PROJECT_ROOT",
    "PROXY",
    "PROXY_MAX_TOKENS",
    "PROXY_MODEL",
    "STREAM_TIMEOUT",
    "Service",
    "TARGET_URL",
    "_OPENAI_API_VALUES",
    "_ResponsesStreamTranslator",
    "_THINKING_MODES",
    "_UPSTREAM_API_VALUES",
    "_anthropic_stop_reason",
    "_apply_reasoning_to_chat",
    "_apply_thinking_to_chat",
    "_auth_file_path",
    "_budget_to_effort",
    "_chat_to_responses_json",
    "_chat_usage_to_responses",
    "_config_file_path",
    "_convert_usage",
    "_default_script_path",
    "_extract_text",
    "_infer_thinking_style",
    "_normalize_openai_url",
    "_project_root",
    "_resolve_api_key",
    "_resolve_config_path",
    "_responses_content_to_text",
    "_responses_to_chat",
    "_responses_url",
    "_stats",
    "_stats_lock",
    "_strip_cache_control",
    "_to_int",
    "_tool_choice_any",
    "convert_request",
    "convert_tool_input",
    "detect_client",
    "get_account_summary",
    "get_stats",
    "is_cache_stats_enabled",
    "load_auth",
    "load_config",
    "logger",
    "normalize_roles",
    "resolve_mode",
    "sse_event",
]